import json
import os
import subprocess
from pathlib import Path
from typing import Any

from automation.engine.context import AutomationContext
from automation.engine.rollback import RollbackManager
from automation.engine.artifacts import artifact_manager
from automation.plugins.base import AutomationPlugin, RiskLevel


class DevPlugin(AutomationPlugin):
    """Development workflow automation plugin."""

    def __init__(self):
        super().__init__()
        self.name = "Development"
        self.description = "Dev workflows: create project, run tests, build, deploy, lint, format"
        self.version = "1.0"
        self.author = "Jarvis"

    def initialize(self):
        self.register_action("dev.create_project", self.create_project, RiskLevel.SAFE)
        self.register_action("dev.run_tests", self.run_tests, RiskLevel.SAFE)
        self.register_action("dev.build", self.build, RiskLevel.MEDIUM)
        self.register_action("dev.lint", self.lint, RiskLevel.SAFE)
        self.register_action("dev.format", self.format_code, RiskLevel.MEDIUM, requires_rollback=True)
        self.register_action("dev.install_deps", self.install_deps, RiskLevel.MEDIUM)
        self.register_action("dev.run_script", self.run_script, RiskLevel.MEDIUM)
        self.register_action("dev.docker_build", self.docker_build, RiskLevel.MEDIUM)
        self.register_action("dev.deploy", self.deploy, RiskLevel.CRITICAL)
        self.register_action("dev.check_ports", self.check_ports, RiskLevel.SAFE)
        self.register_action("dev.kill_port", self.kill_port, RiskLevel.HIGH)

        self.register_workflow({
            "id": "dev_ci_workflow",
            "name": "CI Pipeline",
            "description": "Install deps, lint, test, build",
            "version": "1.0",
            "variables": {"project_path": "."},
            "steps": [
                {"name": "install_deps", "type": "action", "action": "dev.install_deps", "params": {"project_path": "{{project_path}}"}},
                {"name": "lint", "type": "action", "action": "dev.lint", "params": {"project_path": "{{project_path}}"}},
                {"name": "test", "type": "action", "action": "dev.run_tests", "params": {"project_path": "{{project_path}}"}},
                {"name": "build", "type": "action", "action": "dev.build", "params": {"project_path": "{{project_path}}"}},
            ],
        })

        self.register_workflow({
            "id": "dev_new_project",
            "name": "Create New Project",
            "description": "Create a new project, init git, install deps",
            "version": "1.0",
            "variables": {"project_name": "my-app", "project_type": "python"},
            "steps": [
                {"name": "create", "type": "action", "action": "dev.create_project", "params": {"name": "{{project_name}}", "type": "{{project_type}}"}},
                {"name": "git_init", "type": "action", "action": "git.init", "params": {"repo_path": "{{project_name}}"}},
                {"name": "install", "type": "action", "action": "dev.install_deps", "params": {"project_path": "{{project_name}}"}},
            ],
        })

    def _run(self, cmd: list[str], cwd: str = ".", timeout: int = 60) -> dict:
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=cwd or None)
            return {"exit_code": result.returncode, "stdout": result.stdout.strip(), "stderr": result.stderr.strip()}
        except Exception as e:
            return {"exit_code": -1, "stdout": "", "stderr": str(e)}

    def create_project(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        name = params.get("name", "new-project")
        project_type = params.get("type", "python")
        parent = params.get("parent", ".")
        project_path = Path(parent) / name

        if project_type == "python":
            project_path.mkdir(parents=True, exist_ok=True)
            (project_path / "requirements.txt").touch()
            (project_path / "main.py").write_text('"""Main entry point."""\n\nif __name__ == "__main__":\n    print("Hello from ' + name + '")\n')
            (project_path / "README.md").write_text(f"# {name}\n\nGenerated by Jarvis Automation.\n")
        elif project_type == "node":
            r = self._run(["npm", "init", "-y"], cwd=str(project_path))
            project_path.mkdir(parents=True, exist_ok=True)
        elif project_type == "react":
            r = self._run(["npx", "create-react-app", name], cwd=parent, timeout=120)
        elif project_type == "fastapi":
            project_path.mkdir(parents=True, exist_ok=True)
            (project_path / "main.py").write_text(
                'from fastapi import FastAPI\n\napp = FastAPI(title="' + name + '")\n\n@app.get("/")\nasync def root():\n    return {"message": "Hello"}\n')
            (project_path / "requirements.txt").write_text("fastapi\nuvicorn\n")
        else:
            project_path.mkdir(parents=True, exist_ok=True)

        rollback.register("dev.create_project", lambda: __import__("shutil").rmtree(project_path, ignore_errors=True), f"Remove {project_path}")
        return {"status": "ok", "path": str(project_path), "type": project_type}

    def run_tests(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        framework = params.get("framework", "pytest")
        if framework == "pytest":
            r = self._run(["python", "-m", "pytest", "-v"], project_path, timeout=120)
        elif framework == "unittest":
            r = self._run(["python", "-m", "unittest", "discover"], project_path, timeout=120)
        elif framework == "jest":
            r = self._run(["npx", "jest"], project_path, timeout=120)
        else:
            r = self._run(["python", "-m", "pytest", "-v"], project_path, timeout=120)
        return {"status": "ok" if r["exit_code"] == 0 else "failed", "exit_code": r["exit_code"], "output": r["stdout"][:5000], "errors": r["stderr"][:2000]}

    def build(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        build_cmd = params.get("command", "python -m build")
        r = self._run(build_cmd.split(), project_path, timeout=120)
        return {"status": "ok" if r["exit_code"] == 0 else "failed", "output": r["stdout"][:5000]}

    def lint(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        linter = params.get("linter", "ruff")
        if linter == "ruff":
            r = self._run(["python", "-m", "ruff", "check", "."], project_path)
        elif linter == "pylint":
            r = self._run(["python", "-m", "pylint", "**/*.py"], project_path, timeout=60)
        elif linter == "flake8":
            r = self._run(["python", "-m", "flake8", "."], project_path)
        elif linter == "eslint":
            r = self._run(["npx", "eslint", "."], project_path, timeout=60)
        else:
            r = self._run(["python", "-m", "ruff", "check", "."], project_path)
        return {"status": "ok" if r["exit_code"] == 0 else "issues_found", "output": r["stdout"][:5000]}

    def format_code(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        formatter = params.get("formatter", "black")
        if formatter == "black":
            r = self._run(["python", "-m", "black", "."], project_path)
        elif formatter == "ruff":
            r = self._run(["python", "-m", "ruff", "format", "."], project_path)
        elif formatter == "prettier":
            r = self._run(["npx", "prettier", "--write", "."], project_path, timeout=60)
        else:
            r = self._run(["python", "-m", "black", "."], project_path)
        return {"status": "ok" if r["exit_code"] == 0 else "error", "output": r["stdout"][:3000]}

    def install_deps(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        manager = params.get("manager", "pip")
        if manager == "pip":
            req_file = Path(project_path) / "requirements.txt"
            if req_file.exists():
                r = self._run(["pip", "install", "-r", "requirements.txt"], project_path, timeout=120)
            else:
                return {"status": "ok", "message": "No requirements.txt found"}
        elif manager == "npm":
            r = self._run(["npm", "install"], project_path, timeout=120)
        elif manager == "yarn":
            r = self._run(["yarn", "install"], project_path, timeout=120)
        else:
            r = self._run(["pip", "install", "-r", "requirements.txt"], project_path, timeout=120)
        return {"status": "ok" if r["exit_code"] == 0 else "error", "output": r["stdout"][:3000]}

    def run_script(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        script = params.get("script", "")
        r = self._run(["python", script], project_path, timeout=120)
        return {"status": "ok" if r["exit_code"] == 0 else "error", "output": r["stdout"][:5000], "errors": r["stderr"][:2000]}

    def docker_build(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        project_path = params.get("project_path", ".")
        tag = params.get("tag", "latest")
        r = self._run(["docker", "build", "-t", tag, "."], project_path, timeout=300)
        return {"status": "ok" if r["exit_code"] == 0 else "error", "output": r["stdout"][:5000]}

    def deploy(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        target = params.get("target", "")
        method = params.get("method", "docker")
        if method == "docker":
            r = self._run(["docker", "compose", "up", "-d"], params.get("project_path", "."), timeout=120)
        elif method == "pm2":
            r = self._run(["pm2", "restart", "all"], params.get("project_path", "."), timeout=60)
        elif method == "systemd":
            r = self._run(["systemctl", "restart", target], timeout=30)
        else:
            return {"status": "error", "error": f"Unknown deploy method: {method}"}
        return {"status": "ok" if r["exit_code"] == 0 else "error", "target": target, "method": method, "output": r["stdout"][:3000]}

    def check_ports(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        r = self._run(["netstat", "-ano"], timeout=10)
        lines = r["stdout"].split("\n")
        ports = []
        for line in lines:
            if "LISTENING" in line:
                parts = line.split()
                if len(parts) >= 4:
                    ports.append({"address": parts[1], "pid": parts[-1]})
        return {"status": "ok", "listening_ports": ports[:30]}

    def kill_port(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        port = params.get("port", 0)
        r = self._run(["powershell", "-Command",
                       f"Get-Process -Id (Get-NetTCPConnection -LocalPort {port}).OwningProcess | Stop-Process -Force"])
        return {"status": "ok" if r["exit_code"] == 0 else "error", "port": port}
    def kill_port(self, params: dict, ctx: AutomationContext, rollback: RollbackManager) -> dict:
        port = params.get("port", 0)
        r = self._run(["powershell", "-Command",
                       f"Get-Process -Id (Get-NetTCPConnection -LocalPort {port}).OwningProcess | Stop-Process -Force"])
        return {"status": "ok" if r["exit_code"] == 0 else "error", "port": port}
